
export const SIGN_UP_DETAILS_REQUEST = 'SIGN_UP_DETAILS_REQUEST';
export const SIGN_UP_DETAILS_SUCCESS = 'SIGN_UP_DETAILS_SUCCESS';
export const SIGN_UP_DETAILS_FAIL = 'SIGN_UP_DETAILS_FAIL';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SAVE_AUTH = 'SAVE_AUTH';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL';

export const SUPPLIER_LIST_REQUEST = 'SUPPLIER_LIST_REQUEST';
export const SUPPLIER_LIST_SUCCESS = 'SUPPLIER_LIST_SUCCESS';
export const SUPPLIER_LIST_FAIL = 'SUPPLIER_LIST_FAIL';


export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL';


export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAIL = 'UPDATE_SUPPLIER_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const PRODUCT_BY_ID_REQUEST = 'PRODUCT_BY_ID_REQUEST';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_FAIL = 'PRODUCT_BY_ID_FAIL';

export const PRODUCT_LEDGER_LIST_REQUEST = 'PRODUCT_LEDGER_LIST_REQUEST';
export const PRODUCT_LEDGER_LIST_SUCCESS = 'PRODUCT_LEDGER_LIST_SUCCESS';
export const PRODUCT_LEDGER_LIST_FAIL = 'PRODUCT_LEDGER_LIST_FAIL';

//Ledgers
export const DEFAULT_LEDGER_REQUEST = 'DEFAULT_LEDGER_REQUEST';
export const DEFAULT_LEDGER_FAIL = 'DEFAULT_LEDGER_FAIL';
export const DEFAULT_LEDGER_SUCCESS = 'DEFAULT_LEDGER_SUCCESS';


export const SALES_LEDGER_REQUEST = 'SALES_LEDGER_REQUEST';
export const SALES_LEDGER_FAIL = 'SALES_LEDGER_FAIL';
export const SALES_LEDGER_SUCCESS = 'SALES_LEDGER_SUCCESS';


export const PURCHASE_LEDGER_REQUEST = 'PURCHASE_LEDGER_REQUEST';
export const PURCHASE_LEDGER_FAIL = 'PURCHASE_LEDGER_FAIL';
export const PURCHASE_LEDGER_SUCCESS = 'PURCHASE_LEDGER_SUCCESS';


export const MY_LEDGER_REQUEST = 'MY_LEDGER_REQUEST';
export const MY_LEDGER_FAIL = 'MY_LEDGER_FAIL';
export const MY_LEDGER_SUCCESS = 'MY_LEDGER_SUCCESS';


export const UPDATE_LEDGER_REQUEST = 'UPDATE_LEDGER_REQUEST';
export const UPDATE_LEDGER_FAIL = 'UPDATE_LEDGER_FAIL';
export const UPDATE_LEDGER_SUCCESS = 'UPDATE_LEDGER_SUCCESS';

export const LEDGER_CATEGORY_REQUEST = 'LEDGER_CATEGORY_REQUEST';
export const LEDGER_CATEGORY_SUCCESS = 'LEDGER_CATEGORY_SUCCESS';
export const LEDGER_CATEGORY_FAIL = 'LEDGER_CATEGORY_FAIL';


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';


export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST';
export const BANK_LIST_FAIL = 'BANK_LIST_FAIL';
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS';


export const BANK_UPDATE_REQUEST = 'BANK_UPDATE_REQUEST';
export const BANK_UPDATE_FAIL = 'BANK_UPDATE_FAIL';
export const BANK_UPDATE_SUCCESS = 'BANK_UPDATE_SUCCESS';


export const SALES_INVOICE_LIST_REQUEST = 'SALES_INVOICE_LIST_REQUEST';
export const SALES_INVOICE_LIST_SUCCESS = 'SALES_INVOICE_LIST_SUCCESS';
export const SALES_INVOICE_LIST_FAIL = 'SALES_INVOICE_LIST_FAIL';


export const SALES_CN_LIST_REQUEST = 'SALES_CN_LIST_REQUEST';
export const SALES_CN_LIST_SUCCESS = 'SALES_CN_LIST_SUCCESS';
export const SALES_CN_LIST_FAIL = 'SALES_CN_LIST_FAIL';


export const PURCHASE_INVOICE_LIST_REQUEST = 'PURCHASE_INVOICE_LIST_REQUEST';
export const PURCHASE_INVOICE_LIST_SUCCESS = 'PURCHASE_INVOICE_LIST_SUCCESS';
export const PURCHASE_INVOICE_LIST_FAIL = 'PURCHASE_INVOICE_LIST_FAIL';


export const PURCHASE_CN_LIST_REQUEST = 'PURCHASE_CN_LIST_REQUEST';
export const PURCHASE_CN_LIST_SUCCESS = 'PURCHASE_CN_LIST_SUCCESS';
export const PURCHASE_CN_LIST_FAIL = 'PURCHASE_CN_LIST_FAIL';

export const JOURNAL_LIST_REQUEST = 'JOURNAL_LIST_REQUEST';
export const JOURNAL_LIST_FAIL = 'JOURNAL_LIST_FAIL';
export const JOURNAL_LIST_SUCCESS = 'JOURNAL_LIST_SUCCESS';

export const TAX_LIST_REQUEST = 'TAX_LIST_REQUEST';
export const TAX_LIST_FAIL = 'TAX_LIST_FAIL';
export const TAX_LIST_SUCCESS = 'TAX_LIST_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const PRE_EDIT_PROFILE_REQUEST = 'PRE_EDIT_PROFILE_REQUEST';
export const PRE_EDIT_PROFILE_FAIL = 'PRE_EDIT_PROFILE_FAIL';
export const PRE_EDIT_PROFILE_SUCCESS = 'PRE_EDIT_PROFILE_SUCCESS';


export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';


export const BANK_ACTIVITY_REQUEST = 'BANK_ACTIVITY_REQUEST';
export const BANK_ACTIVITY_FAIL = 'BANK_ACTIVITY_FAIL';
export const BANK_ACTIVITY_SUCCESS = 'BANK_ACTIVITY_SUCCESS';


export const BANK_RECONCILE_REQUEST = 'BANK_RECONCILE_REQUEST';
export const BANK_RECONCILE_FAIL = 'BANK_RECONCILE_FAIL';
export const BANK_RECONCILE_SUCCESS = 'BANK_RECONCILE_SUCCESS';

export const CUSTOMER_PAYMENT_REQUEST = 'CUSTOMER_PAYMENT_REQUEST';
export const CUSTOMER_PAYMENT_FAIL = 'CUSTOMER_PAYMENT_FAIL';
export const CUSTOMER_PAYMENT_SUCCESS = 'CUSTOMER_PAYMENT_SUCCESS';


export const SUPPLIER_PAYMENT_REQUEST = 'SUPPLIER_PAYMENT_REQUEST';
export const SUPPLIER_PAYMENT_FAIL = 'SUPPLIER_PAYMENT_FAIL';
export const SUPPLIER_PAYMENT_SUCCESS = 'SUPPLIER_PAYMENT_SUCCESS';


export const SUPPLIER_REFUND_RECEIPT_REQUEST = 'SUPPLIER_REFUND_RECEIPT_REQUEST';
export const SUPPLIER_REFUND_RECEIPT_SUCCESS = 'SUPPLIER_REFUND_RECEIPT_SUCCESS';
export const SUPPLIER_REFUND_RECEIPT_FAIL = 'SUPPLIER_REFUND_RECEIPT_FAIL';

export const SUPPLIER_REFUND_REQUEST = 'SUPPLIER_REFUND_REQUEST';
export const SUPPLIER_REFUND_SUCCESS = 'SUPPLIER_REFUND_SUCCESS';
export const SUPPLIER_REFUND_FAIL = 'SUPPLIER_REFUND_FAIL';
