name: Build Taxgo Release APK
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Release APK
        run: |
          cd android && ./gradlew clean assembleRelease
      - name: Upload Release APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Build Release Bundle
        run: |
          cd android && ./gradlew clean bundleRelease
      - name: Upload Release Bundle
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/
